# Generated by Django 5.2.4 on 2025-07-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watchedmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedMovie',
            new_name='Viewing',
        ),
        migrations.RenameField(
            model_name='viewing',
            old_name='watched_date',
            new_name='view_date',
        ),
    ]
