# Generated by Django 5.2.4 on 2025-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_watchedmovie_viewing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='personal_rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
    ]
