# Generated by Django 5.2.4 on 2025-07-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='main_app.movie'),
        ),
    ]
