# Generated by Django 5.2.4 on 2025-07-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_viewing_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={},
        ),
    ]
