# Generated by Django 5.2.4 on 2025-07-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_viewing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ['-view_date']},
        ),
    ]
